name: 1.开始申请您的子域名
description: 如果您想申请子域名请选择这个
labels: ["申请"]
assignees:
  - RealLanta
body:
  - type: markdown
    attributes:
      value: |
        请在标题中写上您的网站名字
  - type: input
    id: name
    attributes:
      label: 网站名字
      description: 将会在 README.md 和 https://www.bangumi.cyou/websites 中展示，您也可以选择不公开
      placeholder: ex. 我的博客
    validations:
      required: true
  - type: checkboxes
    id: checkagain
    attributes:
      label: 公开我的域名？
      description: |
        将会在 README.md 和 https://www.bangumi.cyou/websites 中展示
      options:
        - label: 公开
          required: true
  - type: input
    id: subdomain
    attributes:
      label: 您想要什么前缀？
      description: |
        例如 xxx.bangumi.cyou
      placeholder: ex. xxx.bangumi.cyou
    validations:
      required: true
  - type: input
    id: resolution-type
    attributes:
      label: 解析类型
      description: |
        支持 A,AAAA,CNAME
      placeholder: ex. A
    validations:
      required: true
  - type: input
    id: resolution-content
    attributes:
      label: 解析内容
      description: |
        支持 IP 或域名(CNAME解析时使用)
      placeholder: ex. 1.1.1.1 或 your-user-name.github.io
    validations:
      required: true
  - type: input
    id: cloudflare
    attributes:
      label: 你需要开启 Cloudflare CDN 吗？
      description: |
        Cloudflare CDN 可以保护您的网站（但是在中国大陆地区会拖慢网站速度）,填写 (y/n)
      placeholder: ex. yes
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 你是一位 Bangumi 用户吗？
      description: |
        请展示您的 Bangumi 的截图
    validations:
      required: false
  - type: checkboxes
    id: checkagain
    attributes:
      label: 警告
      description: |
        作为存储库的所有者，您可以完全控制已发布的内容。 但这也意味着发布网站所带来的所有权利和义务仍由您负责。
      options:
        - label: 我知道了
          required: true
